version: "3"
services:
  api:
    build:
      context: ../verivox-api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    restart: unless-stopped
